lane :test do

   scan(
    code_coverage: true,
    scheme: "ConnectMusics"
   )
   xcov(
    scheme: "ConnectMusics"
   )

end

lane :deployementPreparation do
  if git_branch() == "master"
    version = get_version_number()
    set_github_release(
      repository_name: "shemana/ConnectMusics",
      name: "ConnectMusics v.#{version}",
      api_token: ENV["GITHUB_TOKEN"],
      tag_name: "v#{version}",
      description: changelog_from_git_commits(),
      commitish: "master"
    )
    pod_push(allow_warnings: true, verbose:true)
  end

end
